import type { components } from '@/api/generated';

export type Agent = components['schemas']['Agent'];
export type AgentStatus = Agent['status'];
export type Project = components['schemas']['Project'];
export type SovereigntyTier = Project['sovereigntyTier'];
export type SessionInfo = components['schemas']['SessionInfo'];
export type AlertItem = components['schemas']['AlertItem'];
export type AlertSeverity = AlertItem['severity'];
export type TaskItem = components['schemas']['TaskItem'];
export type Notification = components['schemas']['Notification'];
export type NoteItem = components['schemas']['NoteItem'];
export type TechDebtItem = components['schemas']['TechDebtItem'];
export type SprintPlanItem = components['schemas']['SprintPlanItem'];
export type RequirementItem = components['schemas']['RequirementItem'];
export type UserStoryItem = components['schemas']['UserStoryItem'];
export type ActivityFeedItem = components['schemas']['ActivityFeedItem'];
export type TimelinePoint = components['schemas']['TimelinePoint'];
export type ModuleCatalogItem = components['schemas']['ModuleCatalogItem'];
export type ModuleDependency = components['schemas']['ModuleDependency'];
export type ModuleChangelogEntry = components['schemas']['ModuleChangelogEntry'];
export type AgentBlueprint = components['schemas']['AgentBlueprint'];
export type SessionHistoryItem = components['schemas']['SessionHistoryItem'];
export type SessionHistoryPoint = components['schemas']['SessionHistoryPoint'];
export type AgentBreakdownItem = components['schemas']['AgentBreakdownItem'];
