import { useMemo, useRef } from 'react';
import { useQuery } from '@tanstack/react-query';
import { cn } from '@/lib/utils';
import { useNavigate } from 'react-router-dom';
import { Hexagon, FileCode, Layout, Upload, ChevronRight, Check, Loader2, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { useWorkspace } from '@/context/WorkspaceContext';
import { useHiveData } from '@/api/queries/useHiveData';
import { api } from '@/api/client';
import { toast } from 'sonner';
import { StepConnectLlms } from './onboarding/StepConnectLlms';
import type { SovereigntyTier } from '@/types/domain';

interface GenesisPlanPhase {
  phase: string;
  tasks: string[];
}
interface GenesisPlanPreview {
  phases: GenesisPlanPhase[];
  requirements: { title: string; priority: string }[];
  roster: { role: string }[];
  estimatedDurationDays: number;
  sourceCharacters: number;
}

// Phase 2 of the redesign: insert Connect-LLMs as step 2, between
// Budget and the CEO Describe chat. The total length stays in lockstep
// with the `nextStep`/`prevStep` clamps below — keep them in sync if
// you ever add or remove a step.
const steps = ['Source', 'Budget', 'Connect LLMs', 'Describe', 'Plan Review'];
const LAST_STEP_INDEX = steps.length - 1;
const PLAN_REVIEW_INDEX = LAST_STEP_INDEX;

export default function Onboarding() {
  const navigate = useNavigate();
  const { onboardingDraft, updateOnboardingDraft, resetOnboardingDraft } = useWorkspace();
  const { addProject } = useHiveData();

  const step = onboardingDraft.step;
  const nextStep = () => updateOnboardingDraft((draft) => ({ ...draft, step: Math.min(draft.step + 1, LAST_STEP_INDEX) }));
  const prevStep = () => updateOnboardingDraft((draft) => ({ ...draft, step: Math.max(draft.step - 1, 0) }));

  // Step gating. The Connect-LLMs step (2) won't let you advance until
  // at least one provider key has been confirmed — without one the CEO
  // chat in the next step would silently fail.
  const canAdvance = useMemo(() => {
    if (step === 2) {
      return onboardingDraft.connectedProviderIds.length > 0;
    }
    return true;
  }, [step, onboardingDraft.connectedProviderIds]);

  const estimatedCost = useMemo(() => {
    const factor = onboardingDraft.tier === 'local' ? 0.6 : 1.4;
    return Math.round(onboardingDraft.agents * 8.5 * factor);
  }, [onboardingDraft.agents, onboardingDraft.tier]);

  const launchProject = () => {
    const trimmedDescription = onboardingDraft.description.trim();
    let sourceDefaultName = 'New Hive Project';
    if (onboardingDraft.source === 'import') {
      sourceDefaultName = 'Imported Workspace';
    } else if (onboardingDraft.source === 'template') {
      sourceDefaultName = 'Template Workspace';
    }
    const generatedName = trimmedDescription
      ? trimmedDescription.split(/\s+/).slice(0, 3).join(' ')
      : sourceDefaultName;

    addProject({
      name: generatedName.replace(/[^\w\s-]/g, '').trim() || 'New Hive Project',
      description: trimmedDescription || 'Autogenerated from onboarding',
      sovereigntyTier: onboardingDraft.tier,
      budgetTotalCents: onboardingDraft.budget * 100,
      status: 'active',
    }).catch(console.error);

    resetOnboardingDraft();
    navigate('/dashboard');
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background p-8">
      <div className="flex items-center gap-2 mb-12">
        {steps.map((label, index) => {
          const stepCircleColorIfCurrent = index === step ? 'bg-primary/20 text-primary border-2 border-primary' : 'bg-surface-2 text-muted-foreground';
          const stepCircleColor = index < step ? 'bg-primary text-primary-foreground' : stepCircleColorIfCurrent;
          const stepContent = index < step ? <Check className="h-3.5 w-3.5" /> : index + 1;
          return (
            <div key={label} className="flex items-center gap-2">
              <div className={cn('flex h-7 w-7 items-center justify-center rounded-full text-xs font-semibold transition-all', stepCircleColor)}>
                {stepContent}
              </div>
              <span className={cn('text-xs hidden sm:block', index === step ? 'text-foreground font-medium' : 'text-muted-foreground')}>{label}</span>
              {index < steps.length - 1 && <div className={cn('h-px w-8', index < step ? 'bg-primary' : 'bg-border')} />}
            </div>
          );
        })}
      </div>

      <div className="w-full max-w-2xl animate-fade-in">
        {step === 0 && (
          <StepSource
            source={onboardingDraft.source}
            onSelect={(source) => updateOnboardingDraft({ source })}
          />
        )}
        {step === 1 && (
          <StepBudget
            budget={onboardingDraft.budget}
            agents={onboardingDraft.agents}
            tier={onboardingDraft.tier}
            _estimatedCost={estimatedCost}
            onBudgetChange={(budget) => updateOnboardingDraft({ budget })}
            onAgentsChange={(agents) => updateOnboardingDraft({ agents })}
            onTierChange={(tier) => updateOnboardingDraft({ tier })}
          />
        )}
        {step === 2 && (
          <StepConnectLlms
            connectedProviderIds={onboardingDraft.connectedProviderIds}
            onChange={(connectedProviderIds) =>
              updateOnboardingDraft({ connectedProviderIds })
            }
          />
        )}
        {step === 3 && (
          <>
            <StepDescribe
              _mode={onboardingDraft.describeMode}
              description={onboardingDraft.description}
              uploadedSpecName={onboardingDraft.uploadedSpecName}
              _onModeChange={(describeMode: 'interview' | 'import') => updateOnboardingDraft({ describeMode })}
              onDescriptionChange={(description) => updateOnboardingDraft({ description })}
              onSpecUpload={(file) =>
                updateOnboardingDraft({
                  uploadedSpecName: file.name,
                  // Use the spec text as the description so the genesis
                  // preview is grounded in it. Cap at 32 KB to keep
                  // request payloads sane.
                  description: file.text.slice(0, 32 * 1024),
                })
              }
            />
            <TeamModeToggle
              teamMode={onboardingDraft.teamMode}
              onChange={(teamMode) => updateOnboardingDraft({ teamMode })}
            />
          </>
        )}
        {step === PLAN_REVIEW_INDEX && (
          <StepPlanReview
            source={onboardingDraft.source}
            budget={onboardingDraft.budget}
            agents={onboardingDraft.agents}
            tier={onboardingDraft.tier}
            _estimatedCost={estimatedCost}
            description={onboardingDraft.description}
          />
        )}

      </div>

      <div className="flex gap-3 mt-8">
        {step > 0 && <Button variant="outline" onClick={prevStep}>Back</Button>}
        <Button
          onClick={step === PLAN_REVIEW_INDEX ? launchProject : nextStep}
          className="gap-1.5"
          disabled={!canAdvance}
          title={canAdvance ? undefined : 'Connect at least one provider to continue'}
        >
          {step === PLAN_REVIEW_INDEX ? 'Launch' : 'Next'} <ChevronRight className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}

function StepSource({
  source,
  onSelect,
}: {
  readonly source: 'scratch' | 'template' | 'import' | null;
  readonly onSelect: (source: 'scratch' | 'template' | 'import') => void;
}) {
  return (
    <div className="space-y-6 text-center">
      <h2 className="text-display-sm">How would you like to start?</h2>
      <p className="text-sm text-muted-foreground">Choose how to initialize your project</p>
      <div className="grid grid-cols-3 gap-4">
        {[
          { id: 'scratch' as const, icon: FileCode, title: 'From Scratch', desc: 'Start with an empty project', disabledReason: null },
          { id: 'template' as const, icon: Layout, title: 'Template', desc: 'Use a pre-built template', disabledReason: 'Requires the Hive central server (not yet available). Coming in a later release.' },
          { id: 'import' as const, icon: Upload, title: 'Import', desc: 'Import existing codebase', disabledReason: 'Local-only feature, but not yet implemented. Planned for a future release.' },
        ].map((option) => (
          <button
            key={option.id}
            onClick={() => option.disabledReason ? undefined : onSelect(option.id)}
            title={option.disabledReason ?? undefined}
            disabled={option.disabledReason !== null}
            className={cn(
              'relative rounded-xl border p-6 text-center transition-all',
              source === option.id ? 'border-primary bg-primary/5 glow-amber' : 'border-border bg-card',
              option.disabledReason ? 'opacity-50 cursor-not-allowed' : 'hover:border-primary/40 cursor-pointer',
            )}
          >
            {option.disabledReason && (
              <div className="absolute top-2 right-2 text-[9px] uppercase tracking-wider text-muted-foreground/70 font-semibold">
                {option.id === 'template' ? 'Server-only' : 'Planned'}
              </div>
            )}
            <option.icon className={cn('h-8 w-8 mx-auto mb-3', source === option.id ? 'text-primary' : 'text-muted-foreground')} />
            <h3 className="text-sm font-semibold mb-1">{option.title}</h3>
            <p className="text-micro text-muted-foreground">{option.desc}</p>
          </button>
        ))}
      </div>
    </div>
  );
}

function StepBudget({
  budget,
  agents,
  tier,
  _estimatedCost,
  onBudgetChange,
  onAgentsChange,
  onTierChange,
}: {
  readonly budget: number;
  readonly agents: number;
  readonly tier: SovereigntyTier;
  readonly _estimatedCost: number;
  readonly onBudgetChange: (budget: number) => void;
  readonly onAgentsChange: (agents: number) => void;
  readonly onTierChange: (tier: SovereigntyTier) => void;
}) {
  return (
    <div className="space-y-8">
      <div className="text-center">
        <h2 className="text-display-sm">Configure Resources</h2>
        <p className="text-sm text-muted-foreground mt-1">Set your budget and agent limits</p>
      </div>

      <div className="space-y-6">
        <div>
          <label htmlFor="onboarding-budget" className="text-sm font-medium">Session Budget</label>
          <p className="text-xs text-muted-foreground mb-3">Maximum spend per session</p>
          <div className="flex items-center gap-4">
            <Slider id="onboarding-budget" value={[budget]} onValueChange={([value]) => onBudgetChange(value)} min={10} max={500} step={10} className="flex-1" />
            <span className="text-lg font-mono font-semibold text-primary w-16 text-right">${budget}</span>
          </div>
        </div>

        <div>
          <label htmlFor="onboarding-agents" className="text-sm font-medium">Max Parallel Running Agents</label>
          <p className="text-xs text-muted-foreground mb-3">Number of concurrent agents</p>
          <div className="flex items-center gap-3">
            <button onClick={() => onAgentsChange(Math.max(1, agents - 1))} className="h-8 w-8 rounded border border-border text-sm hover:bg-surface-2">-</button>
            <span id="onboarding-agents" className="text-lg font-mono font-semibold w-8 text-center">{agents}</span>
            <button onClick={() => onAgentsChange(Math.min(12, agents + 1))} className="h-8 w-8 rounded border border-border text-sm hover:bg-surface-2">+</button>
          </div>
        </div>

        <div>
          <label htmlFor="onboarding-tier" className="text-sm font-medium">Sovereignty Tier</label>
          <p className="text-xs text-muted-foreground mb-3">Data processing location</p>
          <div id="onboarding-tier" className="flex gap-2">
            <button onClick={() => onTierChange('local')} className={cn('rounded-lg border px-4 py-2 text-xs capitalize transition-all', tier === 'local' ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:text-foreground')}>
              Local
            </button>
            <button disabled className="rounded-lg border px-4 py-2 text-xs capitalize transition-all border-border text-muted-foreground opacity-50 cursor-not-allowed" title="Coming Soon (Enterprise)">
              Cloud <span className="ml-1 text-[10px] uppercase text-muted-foreground/70 tracking-wider">Coming Soon</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}

function StepDescribe({
  _mode,
  description,
  uploadedSpecName,
  _onModeChange,
  onDescriptionChange,
  onSpecUpload,
}: {
  readonly _mode: 'interview' | 'import';
  readonly description: string;
  readonly uploadedSpecName: string | null;
  readonly _onModeChange: (mode: 'interview' | 'import') => void;
  readonly onDescriptionChange: (description: string) => void;
  readonly onSpecUpload: (file: { name: string; text: string }) => void;
}) {
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    if (file.size > 5 * 1024 * 1024) {
      toast.error('Spec file too large (max 5 MB)');
      return;
    }
    try {
      const text = await file.text();
      onSpecUpload({ name: file.name, text });
      toast.success(`Loaded ${file.name}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to read file');
    }
  };
  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="text-display-sm">Describe Your Project</h2>
        <p className="text-sm text-muted-foreground mt-1">Tell us what you want to build</p>
      </div>

      <div className="rounded-lg border border-border bg-card p-4 space-y-3 relative">
        <div className="flex gap-3">
          <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-primary/10">
            <Hexagon className="h-4 w-4 text-primary" />
          </div>
          <div className="rounded-lg bg-surface-2 px-4 py-2.5 text-sm">
            What type of application are you building? (e.g., web app, API, mobile backend, data pipeline)
          </div>
        </div>
        
        <div className="relative">
          <textarea
            value={description}
            onChange={(event) => onDescriptionChange(event.target.value)}
            className="w-full rounded-lg border border-border bg-surface-2 p-3 pb-12 text-sm placeholder:text-muted-foreground resize-none h-40"
            placeholder="Type your answer, or upload a spec document..."
          />
          
          <div className="absolute bottom-3 left-3 flex items-center gap-2">
            <input
              ref={fileInputRef}
              type="file"
              accept=".md,.txt,.markdown,.text"
              onChange={(event) => handleFileChange(event)}
              className="hidden"
            />
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              className="flex items-center gap-1.5 rounded-md border border-border bg-background px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-surface-2 hover:text-foreground transition-colors"
              title="Upload spec (.md, .txt)"
            >
              <Upload className="h-3.5 w-3.5" />
              Upload Spec
            </button>
            {uploadedSpecName && (
              <span className="text-xs text-muted-foreground bg-background px-2 py-1 rounded border border-border">
                {uploadedSpecName}
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function StepPlanReview({
  source,
  budget,
  agents,
  tier,
  _estimatedCost,
  description,
}: {
  readonly source: 'scratch' | 'template' | 'import' | null;
  readonly budget: number;
  readonly agents: number;
  readonly tier: SovereigntyTier;
  readonly _estimatedCost: number;
  readonly description: string;
}) {
  // Real preview from the backend, grounded in the user's description.
  const previewQuery = useQuery({
    queryKey: ['genesis-preview', description, agents],
    queryFn: () =>
      api<GenesisPlanPreview>('/v1/projects/genesis/preview', {
        method: 'POST',
        body: JSON.stringify({ description, agentCount: agents }),
      }),
    enabled: description.trim().length > 0,
    staleTime: 60_000,
  });

  const generatedPlan = previewQuery.data?.phases ?? [];

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="text-display-sm">Review Your Plan</h2>
        <p className="text-sm text-muted-foreground mt-1">
          {previewQuery.isLoading
            ? 'Generating plan…'
            : 'The hive has generated your project plan'}
        </p>
      </div>

      <div className="rounded-lg border border-border bg-card p-4 text-xs text-muted-foreground space-y-1">
        <div><span className="text-foreground font-medium">Source:</span> {source ?? 'scratch'}</div>
        <div><span className="text-foreground font-medium">Budget:</span> ${budget}</div>
        <div><span className="text-foreground font-medium">Agents:</span> {agents}</div>
        <div><span className="text-foreground font-medium">Tier:</span> {tier}</div>
        {description && <div><span className="text-foreground font-medium">Brief:</span> {description}</div>}
      </div>

      <div className="space-y-3">
        {previewQuery.isLoading && (
          <div className="rounded-lg border border-dashed border-border p-6 text-center text-xs text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin mx-auto mb-2" />
            Generating plan from your description…
          </div>
        )}
        {previewQuery.isError && (
          <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-xs">
            <div className="font-medium text-destructive mb-1">
              Couldn't generate the plan.
            </div>
            <div className="text-muted-foreground mb-2">
              {previewQuery.error instanceof Error
                ? previewQuery.error.message
                : 'Unknown error'}
            </div>
            <button
              type="button"
              onClick={() => void previewQuery.refetch()}
              className="rounded-md border border-border px-3 py-1.5 text-xs text-foreground hover:bg-surface-2"
            >
              Retry
            </button>
          </div>
        )}
        {!previewQuery.isLoading && !previewQuery.isError && generatedPlan.length === 0 && (
          <div className="rounded-lg border border-dashed border-border p-6 text-center text-xs text-muted-foreground">
            Add a description to see a generated plan.
          </div>
        )}
        {generatedPlan.map((phase) => (
          <div key={phase.phase} className="rounded-lg border border-border bg-card p-4">
            <h3 className="text-sm font-semibold mb-2">{phase.phase}</h3>
            <div className="space-y-1">
              {phase.tasks.map((task) => (
                <div key={task} className="flex items-center gap-2 text-xs text-muted-foreground">
                  <div className="h-1.5 w-1.5 rounded-full bg-primary/40" />
                  {task}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <div className="rounded-lg border border-primary/20 bg-primary/5 p-4 text-center">
        <span className="text-sm font-medium">
          {agents} agents • {generatedPlan.length || 3} phases
        </span>
      </div>
    </div>
  );
}



// Phase 2: Team-mode toggle for the CEO chat. When ON, the CEO is
// allowed to delegate to its base team (research / architect / product
// blueprints — added by the runtime side of Phase 1b). When OFF, it
// works alone with degraded research quality. We only persist the
// preference here; the runtime reads it on `/coordinator/converse`.
function TeamModeToggle({
  teamMode,
  onChange,
}: {
  readonly teamMode: boolean;
  readonly onChange: (next: boolean) => void;
}) {
  return (
    <div className="mt-6 rounded-lg border border-border bg-card p-4">
      <div className="flex items-start gap-3">
        <Users className={cn('mt-0.5 h-5 w-5', teamMode ? 'text-primary' : 'text-muted-foreground')} />
        <div className="flex-1">
          <div className="flex items-center justify-between gap-4">
            <h3 className="text-sm font-semibold">Team mode</h3>
            <button
              type="button"
              role="switch"
              aria-checked={teamMode}
              onClick={() => onChange(!teamMode)}
              className={cn(
                'relative h-5 w-9 rounded-full border transition-colors',
                teamMode
                  ? 'border-primary bg-primary/20'
                  : 'border-border bg-surface-2',
              )}
            >
              <span
                className={cn(
                  'absolute top-0.5 h-3.5 w-3.5 rounded-full transition-all',
                  teamMode ? 'left-[18px] bg-primary' : 'left-0.5 bg-muted-foreground',
                )}
              />
            </button>
          </div>
          <p className="mt-1 text-xs text-muted-foreground">
            With team mode on, the CEO delegates research and design to specialised
            agents — higher-quality output, slightly higher cost. With it off, the
            CEO works alone using direct web search; faster and cheaper, but the
            spec doc tends to be thinner.
          </p>
        </div>
      </div>
    </div>
  );
}
