import { useEffect, useMemo, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { cn } from '@/lib/utils';
import { useNavigate } from 'react-router-dom';
import { Hexagon, FileCode, Layout, Upload, ChevronRight, Check, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Progress } from '@/components/ui/progress';
import { useWorkspace } from '@/context/WorkspaceContext';
import { useHiveData } from '@/api/queries/useHiveData';
import { api } from '@/api/client';
import { toast } from 'sonner';

interface GenesisPlanPhase {
  phase: string;
  tasks: string[];
}
interface GenesisPlanPreview {
  phases: GenesisPlanPhase[];
  requirements: { title: string; priority: string }[];
  roster: { role: string }[];
  estimatedDurationDays: number;
  sourceCharacters: number;
}

const steps = ['Source', 'Budget', 'Describe', 'Plan Review', 'Launch'];

export default function Onboarding() {
  const navigate = useNavigate();
  const { onboardingDraft, updateOnboardingDraft, resetOnboardingDraft } = useWorkspace();
  const { addProject } = useHiveData();

  const step = onboardingDraft.step;
  const nextStep = () => updateOnboardingDraft((draft) => ({ ...draft, step: Math.min(draft.step + 1, 4) }));
  const prevStep = () => updateOnboardingDraft((draft) => ({ ...draft, step: Math.max(draft.step - 1, 0) }));

  const estimatedCost = useMemo(() => {
    const factorIfHybrid = onboardingDraft.tier === 'hybrid' ? 1 : 1.4;
    const factor = onboardingDraft.tier === 'local' ? 0.6 : factorIfHybrid;
    return Math.round(onboardingDraft.agents * 8.5 * factor);
  }, [onboardingDraft.agents, onboardingDraft.tier]);

  const launchProject = () => {
    const trimmedDescription = onboardingDraft.description.trim();
    let sourceDefaultName = 'New Hive Project';
    if (onboardingDraft.source === 'import') {
      sourceDefaultName = 'Imported Workspace';
    } else if (onboardingDraft.source === 'template') {
      sourceDefaultName = 'Template Workspace';
    }
    const generatedName = trimmedDescription
      ? trimmedDescription.split(/\s+/).slice(0, 3).join(' ')
      : sourceDefaultName;

    addProject({
      name: generatedName.replace(/[^\w\s-]/g, '').trim() || 'New Hive Project',
      description: trimmedDescription || 'Autogenerated from onboarding',
      sovereigntyTier: onboardingDraft.tier,
      budgetTotalCents: onboardingDraft.budget * 100,
      status: 'active',
    }).catch(console.error);

    resetOnboardingDraft();
    navigate('/dashboard');
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background p-8">
      <div className="flex items-center gap-2 mb-12">
        {steps.map((label, index) => {
          const stepCircleColorIfCurrent = index === step ? 'bg-primary/20 text-primary border-2 border-primary' : 'bg-surface-2 text-muted-foreground';
          const stepCircleColor = index < step ? 'bg-primary text-primary-foreground' : stepCircleColorIfCurrent;
          const stepContent = index < step ? <Check className="h-3.5 w-3.5" /> : index + 1;
          return (
            <div key={label} className="flex items-center gap-2">
              <div className={cn('flex h-7 w-7 items-center justify-center rounded-full text-xs font-semibold transition-all', stepCircleColor)}>
                {stepContent}
              </div>
              <span className={cn('text-xs hidden sm:block', index === step ? 'text-foreground font-medium' : 'text-muted-foreground')}>{label}</span>
              {index < steps.length - 1 && <div className={cn('h-px w-8', index < step ? 'bg-primary' : 'bg-border')} />}
            </div>
          );
        })}
      </div>

      <div className="w-full max-w-2xl animate-fade-in">
        {step === 0 && (
          <StepSource
            source={onboardingDraft.source}
            onSelect={(source) => updateOnboardingDraft({ source })}
          />
        )}
        {step === 1 && (
          <StepBudget
            budget={onboardingDraft.budget}
            agents={onboardingDraft.agents}
            tier={onboardingDraft.tier}
            estimatedCost={estimatedCost}
            onBudgetChange={(budget) => updateOnboardingDraft({ budget })}
            onAgentsChange={(agents) => updateOnboardingDraft({ agents })}
            onTierChange={(tier) => updateOnboardingDraft({ tier })}
          />
        )}
        {step === 2 && (
          <StepDescribe
            mode={onboardingDraft.describeMode}
            description={onboardingDraft.description}
            uploadedSpecName={onboardingDraft.uploadedSpecName}
            onModeChange={(describeMode) => updateOnboardingDraft({ describeMode })}
            onDescriptionChange={(description) => updateOnboardingDraft({ description })}
            onSpecUpload={(file) =>
              updateOnboardingDraft({
                uploadedSpecName: file.name,
                // Use the spec text as the description so the genesis
                // preview is grounded in it. Cap at 32 KB to keep
                // request payloads sane.
                description: file.text.slice(0, 32 * 1024),
              })
            }
          />
        )}
        {step === 3 && (
          <StepPlanReview
            source={onboardingDraft.source}
            budget={onboardingDraft.budget}
            agents={onboardingDraft.agents}
            tier={onboardingDraft.tier}
            estimatedCost={estimatedCost}
            description={onboardingDraft.description}
          />
        )}
        {step === 4 && <StepLaunch onComplete={launchProject} />}
      </div>

      {step < 4 && (
        <div className="flex gap-3 mt-8">
          {step > 0 && <Button variant="outline" onClick={prevStep}>Back</Button>}
          <Button onClick={nextStep} className="gap-1.5">
            {step === 3 ? 'Launch' : 'Next'} <ChevronRight className="h-4 w-4" />
          </Button>
        </div>
      )}
    </div>
  );
}

function StepSource({
  source,
  onSelect,
}: {
  readonly source: 'scratch' | 'template' | 'import' | null;
  readonly onSelect: (source: 'scratch' | 'template' | 'import') => void;
}) {
  return (
    <div className="space-y-6 text-center">
      <h2 className="text-display-sm">How would you like to start?</h2>
      <p className="text-sm text-muted-foreground">Choose how to initialize your project</p>
      <div className="grid grid-cols-3 gap-4">
        {[
          { id: 'scratch' as const, icon: FileCode, title: 'From Scratch', desc: 'Start with an empty project' },
          { id: 'template' as const, icon: Layout, title: 'Template', desc: 'Use a pre-built template' },
          { id: 'import' as const, icon: Upload, title: 'Import', desc: 'Import existing codebase' },
        ].map((option) => (
          <button
            key={option.id}
            onClick={() => onSelect(option.id)}
            className={cn('rounded-xl border p-6 text-center transition-all hover:border-primary/40', source === option.id ? 'border-primary bg-primary/5 glow-amber' : 'border-border bg-card')}
          >
            <option.icon className={cn('h-8 w-8 mx-auto mb-3', source === option.id ? 'text-primary' : 'text-muted-foreground')} />
            <h3 className="text-sm font-semibold mb-1">{option.title}</h3>
            <p className="text-micro text-muted-foreground">{option.desc}</p>
          </button>
        ))}
      </div>
    </div>
  );
}

type SovereigntyTier = 'local' | 'hybrid' | 'cloud';

function StepBudget({
  budget,
  agents,
  tier,
  estimatedCost,
  onBudgetChange,
  onAgentsChange,
  onTierChange,
}: {
  readonly budget: number;
  readonly agents: number;
  readonly tier: SovereigntyTier;
  readonly estimatedCost: number;
  readonly onBudgetChange: (budget: number) => void;
  readonly onAgentsChange: (agents: number) => void;
  readonly onTierChange: (tier: SovereigntyTier) => void;
}) {
  return (
    <div className="space-y-8">
      <div className="text-center">
        <h2 className="text-display-sm">Configure Resources</h2>
        <p className="text-sm text-muted-foreground mt-1">Set your budget and agent limits</p>
      </div>

      <div className="space-y-6">
        <div>
          <label htmlFor="onboarding-budget" className="text-sm font-medium">Session Budget</label>
          <p className="text-xs text-muted-foreground mb-3">Maximum spend per session</p>
          <div className="flex items-center gap-4">
            <Slider id="onboarding-budget" value={[budget]} onValueChange={([value]) => onBudgetChange(value)} min={10} max={500} step={10} className="flex-1" />
            <span className="text-lg font-mono font-semibold text-primary w-16 text-right">${budget}</span>
          </div>
        </div>

        <div>
          <label htmlFor="onboarding-agents" className="text-sm font-medium">Max Agents</label>
          <p className="text-xs text-muted-foreground mb-3">Number of concurrent agents</p>
          <div className="flex items-center gap-3">
            <button onClick={() => onAgentsChange(Math.max(1, agents - 1))} className="h-8 w-8 rounded border border-border text-sm hover:bg-surface-2">-</button>
            <span id="onboarding-agents" className="text-lg font-mono font-semibold w-8 text-center">{agents}</span>
            <button onClick={() => onAgentsChange(Math.min(12, agents + 1))} className="h-8 w-8 rounded border border-border text-sm hover:bg-surface-2">+</button>
          </div>
        </div>

        <div>
          <label htmlFor="onboarding-tier" className="text-sm font-medium">Sovereignty Tier</label>
          <p className="text-xs text-muted-foreground mb-3">Data processing location</p>
          <div id="onboarding-tier" className="flex gap-2">
            {(['local', 'hybrid', 'cloud'] as const).map((option) => (
              <button key={option} onClick={() => onTierChange(option)} className={cn('rounded-lg border px-4 py-2 text-xs capitalize transition-all', tier === option ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:text-foreground')}>
                {option}
              </button>
            ))}
          </div>
        </div>

        <div className="rounded-lg border border-primary/20 bg-primary/5 p-4">
          <span className="text-xs text-muted-foreground">Estimated session cost</span>
          <span className="block text-xl font-mono font-bold text-primary mt-1">${estimatedCost}</span>
          <span className="text-micro text-muted-foreground">{agents} agents × ~$8.50/agent ({tier} tier)</span>
        </div>
      </div>
    </div>
  );
}

function StepDescribe({
  mode,
  description,
  uploadedSpecName,
  onModeChange,
  onDescriptionChange,
  onSpecUpload,
}: {
  readonly mode: 'interview' | 'import';
  readonly description: string;
  readonly uploadedSpecName: string | null;
  readonly onModeChange: (mode: 'interview' | 'import') => void;
  readonly onDescriptionChange: (description: string) => void;
  readonly onSpecUpload: (file: { name: string; text: string }) => void;
}) {
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    if (file.size > 5 * 1024 * 1024) {
      toast.error('Spec file too large (max 5 MB)');
      return;
    }
    try {
      const text = await file.text();
      onSpecUpload({ name: file.name, text });
      toast.success(`Loaded ${file.name}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to read file');
    }
  };
  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="text-display-sm">Describe Your Project</h2>
        <p className="text-sm text-muted-foreground mt-1">Tell us what you want to build</p>
      </div>

      <div className="flex gap-2 justify-center">
        <button onClick={() => onModeChange('interview')} className={cn('rounded-lg border px-4 py-2 text-xs', mode === 'interview' ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground')}>
          Interview Mode
        </button>
        <button onClick={() => onModeChange('import')} className={cn('rounded-lg border px-4 py-2 text-xs', mode === 'import' ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground')}>
          Import Spec
        </button>
      </div>

      {mode === 'interview' ? (
        <div className="rounded-lg border border-border bg-card p-4 space-y-3">
          <div className="flex gap-3">
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-primary/10">
              <Hexagon className="h-4 w-4 text-primary" />
            </div>
            <div className="rounded-lg bg-surface-2 px-4 py-2.5 text-sm">
              What type of application are you building? (e.g., web app, API, mobile backend, data pipeline)
            </div>
          </div>
          <textarea
            value={description}
            onChange={(event) => onDescriptionChange(event.target.value)}
            className="w-full rounded-lg border border-border bg-surface-2 p-3 text-sm placeholder:text-muted-foreground resize-none h-24"
            placeholder="Type your answer..."
          />
        </div>
      ) : (
        <>
          <input
            ref={fileInputRef}
            type="file"
            accept=".md,.txt,.markdown,.text"
            onChange={(event) => void handleFileChange(event)}
            className="hidden"
          />
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            className="w-full rounded-xl border-2 border-dashed border-border bg-card/50 p-12 text-center hover:border-primary/40 transition-colors"
          >
            <Upload className="h-10 w-10 text-muted-foreground mx-auto mb-3" />
            <p className="text-sm text-muted-foreground">
              {uploadedSpecName ? `Loaded ${uploadedSpecName}` : 'Click to choose a spec document'}
            </p>
            <p className="text-micro text-muted-foreground mt-1">.md, .txt (PDF/DOCX support deferred)</p>
          </button>
        </>
      )}
    </div>
  );
}

function StepPlanReview({
  source,
  budget,
  agents,
  tier,
  estimatedCost,
  description,
}: {
  readonly source: 'scratch' | 'template' | 'import' | null;
  readonly budget: number;
  readonly agents: number;
  readonly tier: 'local' | 'hybrid' | 'cloud';
  readonly estimatedCost: number;
  readonly description: string;
}) {
  // Real preview from the backend, grounded in the user's description.
  const previewQuery = useQuery({
    queryKey: ['genesis-preview', description, agents],
    queryFn: () =>
      api<GenesisPlanPreview>('/v1/projects/genesis/preview', {
        method: 'POST',
        body: JSON.stringify({ description, agentCount: agents }),
      }),
    enabled: description.trim().length > 0,
    staleTime: 60_000,
  });

  const generatedPlan = previewQuery.data?.phases ?? [];

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="text-display-sm">Review Your Plan</h2>
        <p className="text-sm text-muted-foreground mt-1">
          {previewQuery.isLoading
            ? 'Generating plan…'
            : 'The hive has generated your project plan'}
        </p>
      </div>

      <div className="rounded-lg border border-border bg-card p-4 text-xs text-muted-foreground space-y-1">
        <div><span className="text-foreground font-medium">Source:</span> {source ?? 'scratch'}</div>
        <div><span className="text-foreground font-medium">Budget:</span> ${budget}</div>
        <div><span className="text-foreground font-medium">Agents:</span> {agents}</div>
        <div><span className="text-foreground font-medium">Tier:</span> {tier}</div>
        {description && <div><span className="text-foreground font-medium">Brief:</span> {description}</div>}
      </div>

      <div className="space-y-3">
        {previewQuery.isLoading && (
          <div className="rounded-lg border border-dashed border-border p-6 text-center text-xs text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin mx-auto mb-2" />
            Generating plan from your description…
          </div>
        )}
        {previewQuery.isError && (
          <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-xs">
            <div className="font-medium text-destructive mb-1">
              Couldn't generate the plan.
            </div>
            <div className="text-muted-foreground mb-2">
              {previewQuery.error instanceof Error
                ? previewQuery.error.message
                : 'Unknown error'}
            </div>
            <button
              type="button"
              onClick={() => void previewQuery.refetch()}
              className="rounded-md border border-border px-3 py-1.5 text-xs text-foreground hover:bg-surface-2"
            >
              Retry
            </button>
          </div>
        )}
        {!previewQuery.isLoading && !previewQuery.isError && generatedPlan.length === 0 && (
          <div className="rounded-lg border border-dashed border-border p-6 text-center text-xs text-muted-foreground">
            Add a description to see a generated plan.
          </div>
        )}
        {generatedPlan.map((phase) => (
          <div key={phase.phase} className="rounded-lg border border-border bg-card p-4">
            <h3 className="text-sm font-semibold mb-2">{phase.phase}</h3>
            <div className="space-y-1">
              {phase.tasks.map((task) => (
                <div key={task} className="flex items-center gap-2 text-xs text-muted-foreground">
                  <div className="h-1.5 w-1.5 rounded-full bg-primary/40" />
                  {task}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <div className="rounded-lg border border-primary/20 bg-primary/5 p-4 text-center">
        <span className="text-sm font-medium">
          Estimated: {agents} agents • ~${estimatedCost} •{' '}
          {generatedPlan.length || 3} phases
        </span>
      </div>
    </div>
  );
}

function StepLaunch({ onComplete }: { readonly onComplete: () => void }) {
  const [progress, setProgress] = useState(0);
  const [countdown, setCountdown] = useState(3);
  const items = ['Initializing workspace...', 'Spawning agents...', 'Loading modules...', 'Starting session...', 'Ready!'];

  useEffect(() => {
    const countdownTimer = globalThis.setInterval(() => {
      setCountdown((value) => {
        if (value <= 1) {
          globalThis.clearInterval(countdownTimer);
          return 0;
        }
        return value - 1;
      });
    }, 700);

    return () => globalThis.clearInterval(countdownTimer);
  }, []);

  useEffect(() => {
    if (countdown > 0) {
      return;
    }

    let stepIndex = 0;
    const progressTimer = globalThis.setInterval(() => {
      stepIndex += 1;
      setProgress(Math.min(stepIndex * 25, 100));
      if (stepIndex >= 5) {
        globalThis.clearInterval(progressTimer);
        globalThis.setTimeout(onComplete, 600);
      }
    }, 500);

    return () => globalThis.clearInterval(progressTimer);
  }, [countdown, onComplete]);

  return (
    <div className="space-y-8 text-center">
      <div>
        <h2 className="text-display-sm">Launching Your Hive</h2>
        <p className="text-sm text-muted-foreground mt-2">
          {countdown > 0 ? `Launch begins in ${countdown}…` : 'Finalizing workspace startup…'}
        </p>
      </div>
      <Progress value={progress} className="h-2 max-w-md mx-auto" />
      <div className="space-y-2">
        {items.map((item, index) => {
          const isComplete = progress >= (index + 1) * 20;
          const isCurrent = !isComplete && progress >= index * 20;
          return (
            <div key={item} className={cn('flex items-center gap-3 justify-center transition-all', isComplete ? 'text-success' : isCurrent ? 'text-foreground' : 'text-muted-foreground/40')}>
              {isComplete ? <Check className="h-4 w-4" /> : isCurrent ? <Loader2 className="h-4 w-4 animate-spin" /> : <div className="h-4 w-4" />}
              <span className="text-sm">{item}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}
