use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum NoteCategory {
    Architecture,
    Decisions,
    Patterns,
    Issues,
    #[serde(rename = "Auto-generated")]
    AutoGenerated,
}

impl std::fmt::Display for NoteCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Architecture => write!(f, "Architecture"),
            Self::Decisions => write!(f, "Decisions"),
            Self::Patterns => write!(f, "Patterns"),
            Self::Issues => write!(f, "Issues"),
            Self::AutoGenerated => write!(f, "Auto-generated"),
        }
    }
}

impl std::str::FromStr for NoteCategory {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Architecture" => Ok(Self::Architecture),
            "Decisions" => Ok(Self::Decisions),
            "Patterns" => Ok(Self::Patterns),
            "Issues" => Ok(Self::Issues),
            "Auto-generated" => Ok(Self::AutoGenerated),
            _ => Err(format!("invalid note category: {s}")),
        }
    }
}
